# Generated by Django 4.1.7 on 2023-03-19 21:28

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('silant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silant.customuser', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='service_company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.customuser', verbose_name='Имя пользователя'),
        ),
    ]
