# Generated by Django 4.1.7 on 2023-02-21 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('silant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='car',
            name='consignee',
            field=models.TextField(blank=True, max_length=50, verbose_name='Грузополучатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_of_shipment_from_the_factory',
            field=models.DateField(blank=True, verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='car',
            name='delivery_address',
            field=models.TextField(blank=True, max_length=150, verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.drive_axle_model', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.engine_model', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.TextField(blank=True, max_length=150, verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='silant.service_company', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steerable_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.steerable_axle_model', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='supply_contract',
            field=models.TextField(blank=True, max_length=50, verbose_name='Договор поставки №, дата.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='technique_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.technique_model', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.transmission_model', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='description_failure',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='description_failure',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='drive_axle_model',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='engine_model',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recovery_method',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recovery_method',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service_company',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='steerable_axle_model',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='technique_model',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transmission_model',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='type_maintenance',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='type_maintenance',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
