# Generated by Django 4.1.7 on 2023-03-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0002_customuser_alter_car_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='delivery_address',
            field=models.TextField(blank=True, max_length=300, verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Комплектация (доп. опции)'),
        ),
    ]
