# Generated by Django 4.1.7 on 2023-03-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0003_alter_car_delivery_address_alter_car_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='parts_used',
            field=models.TextField(blank=True, verbose_name='Используемые запасные части'),
        ),
    ]
