# Generated by Django 4.1.7 on 2023-02-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0003_alter_car_client_alter_car_service_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_of_shipment_from_the_factory',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки с завода'),
        ),
    ]
