# Generated by Django 4.1.7 on 2023-02-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0004_alter_car_date_of_shipment_from_the_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_of_shipment_from_the_factory',
            field=models.DateField(verbose_name='Дата отгрузки с завода'),
        ),
    ]
