# Generated by Django 4.1.7 on 2023-02-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0005_alter_car_date_of_shipment_from_the_factory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машины', 'verbose_name_plural': 'Машины'},
        ),
    ]
