# Generated by Django 4.1.7 on 2023-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0006_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_of_shipment_from_the_factory',
            field=models.DateField(db_index=True, verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='car',
            name='factory_number',
            field=models.TextField(db_index=True, max_length=17, unique=True, verbose_name='Заводской номер'),
        ),
    ]
