# Generated by Django 4.1.7 on 2023-02-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0007_alter_car_date_of_shipment_from_the_factory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['date_of_shipment_from_the_factory'], 'verbose_name': 'Машины', 'verbose_name_plural': 'Машины'},
        ),
    ]
