# Generated by Django 4.1.7 on 2023-03-04 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0008_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silant.service_company', verbose_name='Сервисная организация'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operating_time',
            field=models.IntegerField(verbose_name='Наработка мотто/часов'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.service_company', verbose_name='Сервисная организация'),
        ),
    ]
