# Generated by Django 4.1.7 on 2023-03-04 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0009_alter_car_service_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.car', verbose_name='Машина'),
        ),
    ]
