# Generated by Django 4.1.7 on 2023-03-04 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0010_alter_maintenance_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.service_company', verbose_name='Сервисная организация'),
        ),
    ]
